var elementos =[
	{nombre:"Hidrogeno",numero:1,simbolo:"H",peso:"1.0079", pertenece:"no metales",grupo:"IA"},
	{nombre:"Helio",numero:2,simbolo:"He",peso:"4,0026", pertenece:"no metales",grupo:"VIIIA"},
	{nombre:"Litio",numero:3,simbolo:"Li",peso:"6.941", pertenece:"metales",grupo:"IA"},
	{nombre:"Berilio",numero:4,simbolo:"Be",peso:"9.0121", pertenece:"metales",grupo:"IIA"},
	{nombre:"Boro",numero:5,simbolo:"B",peso:"10.811",pertenece:"metaloides",grupo:"IIIA"},
	{nombre:"Carbono",numero:6,simbolo:"C",peso:"12.011",pertenece:"no metales",grupo:"IVA"},
	{nombre:"Nitrogeno",numero:7,simbolo:"N",peso:"14.0067",pertenece:"no metales",grupo:"VA"},
	{nombre:"Oxigeno",numero:8,simbolo:"O",peso:"15.9994",pertenece:"no metales",grupo:"VIA"},
	{nombre:"Fluor",numero:9,simbolo:"F",peso:"18.9984",pertenece:"no metales",grupo:"VIIA"},
	{nombre:"Neon",numero:10,simbolo:"Ne",peso:"20.1797",pertenece:"no metales",grupo:"VIIIA"},
	{nombre:"Sodio",numero:11,simbolo:"Na",peso:"22.9897",pertenece:"metales",grupo:"IA"},
	{nombre:"Magnesio",numero:12,simbolo:"Mg",peso:"24.3050",pertenece:"metales",grupo:"IIA"},
	{nombre:"Aluminio",numero:13,simbolo:"Al",peso:"26.9815",pertenece:"metales",grupo:"IIIA"},
	{nombre:"Silicio",numero:14,simbolo:"Si",peso:"28.0855",pertenece:"metaloides",grupo:"IVA"},
	{nombre:"Fósforo",numero:15,simbolo:"P",peso:"30.9737",pertenece:"no metales",grupo:"VA"},
	{nombre:"Azufre",numero:16,simbolo:"S",peso:"32.066",pertenece:"no metales",grupo:"VIA"},
	{nombre:"Cloro",numero:17,simbolo:"Cl",peso:"35.4527",pertenece:"no metales",grupo:"VIIA"},
	{nombre:"Argón",numero:18,simbolo:"Ar",peso:"39.948",pertenece:"no metales",grupo:"VIIIA"},
	{nombre:"Potasio",numero:19,simbolo:"K",peso:"39.0983",pertenece:"metales",grupo:"IA"},
	{nombre:"Calcio",numero:20,simbolo:"Ca",peso:"40.078",pertenece:"metales",grupo:"IIA"},
	{nombre:"Escandio",numero:21,simbolo:"Sc",peso:"44.9559",pertenece:"metales",grupo:"IIIB"},
	{nombre:"Titanio",numero:22,simbolo:"Ti",peso:"47.88",pertenece:"metales",grupo:"IVB"},
	{nombre:"Vanadio",numero:23,simbolo:"V",peso:"50.9415",pertenece:"metales",grupo:"VB"},
	{nombre:"Cromo",numero:24,simbolo:"Cr",peso:"51.9961",pertenece:"metales",grupo:"VIB"},
	{nombre:"Manganeso",numero:25,simbolo:"Mn",peso:"54.9380",pertenece:"metales",grupo:"VIIB"},
	{nombre:"Hierro",numero:26,simbolo:"Fe",peso:"55.847",pertenece:"metales",grupo:"VIIIB1"},
	{nombre:"Cobalto",numero:27,simbolo:"Co",peso:"58.9332",pertenece:"metales",grupo:"VIIIB2"},
	{nombre:"Niquel",numero:28,simbolo:"Ni",peso:"58.69",pertenece:"metales",grupo:"VIIIB3"},
	{nombre:"Cobre",numero:29,simbolo:"Cu",peso:"63.546",pertenece:"metales",grupo:"IB"},
	{nombre:"Zinc",numero:30,simbolo:"Zn",peso:"65.39",pertenece:"metales",grupo:"IIB"},
	{nombre:"Galio",numero:31,simbolo:"Ga",peso:"69.723",pertenece:"metales",grupo:"IIIA"},
	{nombre:"Germanio",numero:32,simbolo:"Ge",peso:"72.61",pertenece:"metaloides",grupo:"IVA"},
	{nombre:"Arsénico",numero:33,simbolo:"As",peso:"74.9215",pertenece:"metaloides",grupo:"VA"},
	{nombre:"Selenio",numero:34,simbolo:"Se",peso:"78.96",pertenece:"no metales",grupo:"VIA"},
	{nombre:"Bromo",numero:35,simbolo:"Br",peso:"79.904",pertenece:"no metales",grupo:"VIIA"},
	{nombre:"Kriptón",numero:36,simbolo:"Kr",peso:"83.80",pertenece:"no metales",grupo:"VIIIA"},
	{nombre:"Rubidio",numero:37,simbolo:"Rb",peso:"85.4678",pertenece:"metales",grupo:"IA"},
	{nombre:"Estroncio",numero:38,simbolo:"Sr",peso:"87.62",pertenece:"metales",grupo:"IIA"},
	{nombre:"Itrio",numero:39,simbolo:"Y",peso:"88.9058",pertenece:"metales",grupo:"IIIB"},
	{nombre:"Circonio",numero:40,simbolo:"Zr",peso:"91.224",pertenece:"metales",grupo:"IVB"},
	{nombre:"Niobio",numero:41,simbolo:"Nb",peso:"92.9063",pertenece:"metales",grupo:"VB"},
	{nombre:"Molibdeno",numero:42,simbolo:"Mo",peso:"95.94",pertenece:"metales",grupo:"VIB"},
	{nombre:"Tecnecio",numero:43,simbolo:"Tc",peso:"98",pertenece:"metales",grupo:"VIIB"},
	{nombre:"Rutenio",numero:44,simbolo:"Ru",peso:"101.07",pertenece:"metales",grupo:"VIIIB1"},
	{nombre:"Rodio",numero:45,simbolo:"Rh",peso:"102.9055",pertenece:"metales",grupo:"VIIIB2"},
	{nombre:"Paladio",numero:46,simbolo:"Pd",peso:"106.42",pertenece:"metales",grupo:"VIIIB3"},
	{nombre:"Plata",numero:47,simbolo:"Ag",peso:"107.8682",pertenece:"metales",grupo:"IB"},
	{nombre:"Cadmio",numero:48,simbolo:"Cd",peso:"112.411",pertenece:"metales",grupo:"IIB"},
	{nombre:"Indio",numero:49,simbolo:"In",peso:"114.82",pertenece:"metales",grupo:"IIIA"},
	{nombre:"Estaño",numero:50,simbolo:"Sn",peso:"118.710",pertenece:"metales",grupo:"IVA"},
	{nombre:"Antimonio",numero:51,simbolo:"Sb",peso:"121.75",pertenece:"metaloides",grupo:"VA"},
	{nombre:"Telurio",numero:52,simbolo:"Te",peso:"127.60",pertenece:"metaloides",grupo:"VIA"},
	{nombre:"Yodo",numero:53,simbolo:"I",peso:"126.9044",pertenece:"no metales",grupo:"VIIA"},
	{nombre:"Xenón",numero:54,simbolo:"Xe",peso:"131.29",pertenece:"no metales",grupo:"VIIIA"},
	{nombre:"Cesio",numero:55,simbolo:"Cs",peso:"132.9054",pertenece:"metales",grupo:"IA"},
	{nombre:"Bario",numero:56,simbolo:"Ba",peso:"137.237",pertenece:"metales",grupo:"IIA"},
	{nombre:"Lantano",numero:57,simbolo:"La",peso:"138.9055",pertenece:"metales",grupo:"IIIB"},
	{nombre:"Cerio",numero:58,simbolo:"Ce",peso:"140.115",pertenece:"metales"},
	{nombre:"Praseodimio",numero:59,simbolo:"Pr",peso:"114.82",pertenece:"metales"},
	{nombre:"Neodimio",numero:60,simbolo:"Nd",peso:"114.82",pertenece:"metales"},
	{nombre:"Prometio",numero:61,simbolo:"Pm",peso:"114.82",pertenece:"metales"},
	{nombre:"Samario",numero:62,simbolo:"Sm",peso:"114.82",pertenece:"metales"},
	{nombre:"Europio",numero:63,simbolo:"Eu",peso:"114.82",pertenece:"metales"},
	{nombre:"Gadolinio",numero:64,simbolo:"Gd",peso:"114.82",pertenece:"metales"},
	{nombre:"Terbio",numero:65,simbolo:"Tb",peso:"114.82",pertenece:"metales"},
	{nombre:"Disprosio",numero:66,simbolo:"Dy",peso:"114.82",pertenece:"metales"},
	{nombre:"Holmio",numero:67,simbolo:"Ho",peso:"114.82",pertenece:"metales"},
	{nombre:"Erbio",numero:68,simbolo:"Er",peso:"114.82",pertenece:"metales"},
	{nombre:"Tulio",numero:69,simbolo:"Tm",peso:"114.82",pertenece:"metales"},
	{nombre:"Iterbio",numero:70,simbolo:"Yb",peso:"114.82",pertenece:"metales"},
	{nombre:"Lutecio",numero:71,simbolo:"Lu",peso:"114.82",pertenece:"metales"},
	{nombre:"Hafnio",numero:72,simbolo:"Hf",peso:"114.82",pertenece:"metales",grupo:"IVB"},
	{nombre:"Tantalio",numero:73,simbolo:"Ta",peso:"114.82",pertenece:"metales",grupo:"VB"},
	{nombre:"Wolframio",numero:74,simbolo:"W",peso:"114.82",pertenece:"metales",grupo:"VIB"},
	{nombre:"Renio",numero:75,simbolo:"Re",peso:"114.82",pertenece:"metales",grupo:"VIIB"},
	{nombre:"Osmio",numero:76,simbolo:"Os",peso:"114.82",pertenece:"metales",grupo:"VIIIB1"},
	{nombre:"Iridio",numero:77,simbolo:"Ir",peso:"114.82",pertenece:"metales",grupo:"VIIIB2"},
	{nombre:"Platino",numero:78,simbolo:"Pt",peso:"114.82",pertenece:"metales",grupo:"VIIIB3"},
	{nombre:"Oro",numero:79,simbolo:"Au",peso:"114.82",pertenece:"metales",grupo:"IB"},
	{nombre:"Mercurio",numero:80,simbolo:"Hg",peso:"114.82",pertenece:"metales",grupo:"IIB"},
	{nombre:"Talio",numero:81,simbolo:"Tl",peso:"114.82",pertenece:"metales",grupo:"IIIA"},
	{nombre:"Plomo",numero:82,simbolo:"Pb",peso:"114.82",pertenece:"metales",grupo:"IVA"},
	{nombre:"Bismuto",numero:83,simbolo:"Bi",peso:"114.82",pertenece:"metales",grupo:"VA"},
	{nombre:"Polonio",numero:84,simbolo:"Po",peso:"114.82",pertenece:"metaloides",grupo:"VIA"},
	{nombre:"Astato",numero:85,simbolo:"At",peso:"114.82",pertenece:"no metales",grupo:"VIIA"},
	{nombre:"Radón",numero:86,simbolo:"Rn",peso:"114.82",pertenece:"no metales",grupo:"VIIIA"},
	{nombre:"Francio",numero:87,simbolo:"Fr",peso:"114.82",pertenece:"metales",grupo:"IA"},
	{nombre:"Radio",numero:88,simbolo:"Ra",peso:"114.82",pertenece:"metales",grupo:"IIA"},
	{nombre:"Actinio",numero:89,simbolo:"Ac",peso:"114.82",pertenece:"metales",grupo:"IIIB"},
	{nombre:"Torio",numero:90,simbolo:"Th",peso:"114.82",pertenece:"metales"},
	{nombre:"Protactinio",numero:91,simbolo:"Pa",peso:"114.82",pertenece:"metales"},
	{nombre:"Uranio",numero:92,simbolo:"U",peso:"114.82",pertenece:"metales"},
	{nombre:"Neptunio",numero:93,simbolo:"Np",peso:"114.82",pertenece:"metales"},
	{nombre:"Plutonio",numero:94,simbolo:"Pu",peso:"114.82",pertenece:"metales"},
	{nombre:"Americio",numero:95,simbolo:"Am",peso:"114.82",pertenece:"metales"},
	{nombre:"Curio",numero:96,simbolo:"Cm",peso:"114.82",pertenece:"metales"},
	{nombre:"Berkelio",numero:97,simbolo:"Bk",peso:"114.82",pertenece:"metales"},
	{nombre:"Californio",numero:98,simbolo:"Cf",peso:"114.82",pertenece:"metales"},
	{nombre:"Einstenio",numero:99,simbolo:"Es",peso:"114.82",pertenece:"metales"},
	{nombre:"Fermio",numero:100,simbolo:"Fm",peso:"114.82",pertenece:"metales"},
	{nombre:"Mendelevio",numero:101,simbolo:"Md",peso:"114.82",pertenece:"metales"},
	{nombre:"Nobelio",numero:102,simbolo:"No",peso:"114.82",pertenece:"metales"},
	{nombre:"Lawrencio",numero:103,simbolo:"Lr",peso:"114.82",pertenece:"metales"},
	{nombre:"Rutherfordio",numero:104,simbolo:"Rf",peso:"114.82",pertenece:"metales",grupo:"IVB"},
	{nombre:"Dubnio",numero:105,simbolo:"Db",peso:"114.82",pertenece:"metales",grupo:"VB"},
	{nombre:"Seaborgio",numero:106,simbolo:"Sg",peso:"114.82",pertenece:"metales",grupo:"VIB"},
	{nombre:"Bohrio",numero:107,simbolo:"Bh",peso:"114.82",pertenece:"metales",grupo:"VIIB"},
	{nombre:"Hassio",numero:108,simbolo:"Hs",peso:"114.82",pertenece:"metales",grupo:"VIIIB1"},
	{nombre:"Meitnerio",numero:109,simbolo:"Mt",peso:"114.82",pertenece:"metales",grupo:"VIIIB2"},
	{nombre:"Darmstadio",numero:110,simbolo:"Ds",peso:"114.82",pertenece:"metales",grupo:"VIIIB3"},
	{nombre:"Roentgenio",numero:111,simbolo:"Rg",peso:"114.82",pertenece:"metales",grupo:"IB"},
	{nombre:"Copernicio",numero:112,simbolo:"Cn",peso:"114.82",pertenece:"metales",grupo:"IIB"},
	{nombre:"Ununtrio",numero:113,simbolo:"Uut",peso:"114.82",pertenece:"metales",grupo:"IIIA"},
	{nombre:"Flerovio",numero:114,simbolo:"Fl",peso:"114.82",pertenece:"metales",grupo:"IVA"},
	{nombre:"Ununpentio",numero:115,simbolo:"Uup",peso:"114.82",pertenece:"metales",grupo:"VA"},
	{nombre:"Livermorio",numero:116,simbolo:"Lv",peso:"114.82",pertenece:"metales",grupo:"VIA"},
	{nombre:"Ununseptio",numero:117,simbolo:"Uus",peso:"114.82",pertenece:"no metales",grupo:"VIIA"},
	{nombre:"Ununoctio",numero:118,simbolo:"Uuo",peso:"114.82",pertenece:"no metales",grupo:"VIIIA"}
];

